[build]
  publish = "build/"
  command = "npm run build"
[[redirects]]
  from = "https://mantle.alley.co/*"
  to = "https://mantle.alley.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://mantle.alley.com/testing-started/test-framework.html"
  to = "https://mantle.alley.com/docs/testing"
  status = 301
  force = true
[[redirects]]
  from = "https://mantle.alley.com/models/querying-models"
  to = "https://mantle.alley.com/docs/models/query-builder"
  status = 301
  force = true